import Link from "next/link";
import Image from "next/image";
import styles from "./page.module.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import "bootstrap/dist/css/bootstrap.min.css";
export const metadata = {
  title: "FESHOP - Products",
  description: "Generated by create next app",
};

async function getData() {
  const res = await fetch("https://dummyjson.com/products");
  if (!res.ok) {
    throw new Error("Failed to fetch data");
  }
  return res.json();
}

export default async function Products() {
  const data = await getData();
  const products = data.products;
  return (
    <div class="row row-cols-1 row-cols-md-2 g-4">
      {products.map((product) => (
        <Link
          href={`/blog/${product.id}`}
          className={styles.post}
          key={product.id}
        >
          <div class="col h-100 ">
            <div class="card h-100 bg-dark">
              <Image
                className={styles.image}
                src={product.thumbnail}
                width={350}
                height={250}
                alt={product.title}
              />
              <div class="card-body">
                <h5 class="card-title text-white">{product.title}</h5>
                <p class="card-text text-white">{product.description}</p>
                <span class={styles.price}>💰 {product.price}$</span>
              </div>
            </div>
          </div>
        </Link>
      ))}
    </div>
  );
}
